version: '3'
services:
  ms-zipkin:
    image: openzipkin/zipkin
    container_name: ms-zipkin
    ports:
      - "9411:9411"
    restart: always
    networks:
      - outside

  ms-elasticsearch:
    image: elasticsearch:7.14.0
    container_name: ms-elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    networks:
      - outside

  ms-kibana:
    image: kibana:7.14.0
    container_name: ms-kibana
    environment:
      ELASTICSEARCH_HOSTS: http://ms-elasticsearch:9200
    ports:
      - "5601:5601"
    restart: always
    networks:
      - outside

  ms-nacos:
    image: nacos/nacos-server:2.0.3
    container_name: ms-nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
#    volumes:
#      - ./ms-nacos/standalone-logs/:/home/nacos/logs
#      - ./ms-nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: always
    networks:
      - outside

  ms-gateway:
    build:
      context: ms-gateway
    container_name: ms-gateway
#    expose:
#      - "8800"
    ports:
      - "8800:8800"
    networks:
      - outside
    restart: always
    depends_on:
      - ms-nacos

  ms-customer:
    build:
      context: ms-customer
    container_name: ms-customer
    expose:
      - "8810"
    ports:
      - "8810:8810"
    networks:
      - outside
    restart: always
    depends_on:
      - ms-nacos

  ms-provider:
    build:
      context: ms-provider
    container_name: ms-provider
    expose:
      - "8820"
    ports:
      - "8820:8820"
    networks:
      - outside
    restart: always
    depends_on:
      - ms-nacos
#networks:
#  default:
#    external:
#      name: outside
#
networks:
  outside:
    external: true