

### customer_host

GET {{gateway_host}}/actuator/prometheus


####
# api
####

GET {{gateway_host}}/api1/customer/test

###

GET {{gateway_host}}/api1/customer/test2

####
# lb api
####

GET {{gateway_host}}/lbapi/customer/test

### RestTemplate
GET {{gateway_host}}/lbapi/customer/test2

### feign
GET {{gateway_host}}/lbapi/customer/test3