server:
  port: 8810

spring:
  application:
    name: ms-customer

feign:
  hystrix:
    enabled: true

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ms-customer
    export:
      prometheus:
        enabled: true